grafana:
  grafana.ini:
    auth:
      disable_login_form: true
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
      org_name: "Main Org."
      org_role: "Viewer" # or "Admin" if you want admin rights for anonymous access
